title: recyclica_dev
email: mail@ikovylyaev.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recyclica.github.io/recyclica-design-resources" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
